### ISSUE TITLE
Fails on password with `$` sign

### ISSUE THREAD

**Issue by dkBrazz** [sebersole/gradle-maven-publish-auth#29]
Plugin fails if the password in settings.xml contains a dollar sign.

settings.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <servers>
        <server>
            <id>snapshots-repo</id>
            <username>ci_user</username>
            <password>42XY$^;!fg9abcdefg$%%%higklmn</password>
        </server>
    </servers>
</settings>
```

Error:
```
Caused by: groovy.lang.GroovyRuntimeException: Failed to parse template script (your template may contain an error or be trying to use expressions not currently supported): startup failed:
GStringTemplateScript10.groovy: 2: illegal string body character after dollar sign;
   solution: either escape a literal dollar sign "\$5" or bracket the value expression "${5}" @ line 2, column 42.
   plate() { return { out -> out << """42XY
                                 ^

1 error

        at org.hibernate.build.publish.auth.maven.pwd.ValueProcessor.processValue(ValueProcessor.java:51)
        at org.hibernate.build.publish.auth.maven.SettingsXmlCredentialsProvider.extractValue(SettingsXmlCredentialsProvider.java:126)
        at org.hibernate.build.publish.auth.maven.SettingsXmlCredentialsProvider.extractCredentials(SettingsXmlCredentialsProvider.java:113)
        at org.hibernate.build.publish.auth.maven.SettingsXmlCredentialsProvider.extractCredentialsFromSettings(SettingsXmlCredentialsProvider.java:89)
        at org.hibernate.build.publish.auth.maven.SettingsXmlCredentialsProvider.<init>(SettingsXmlCredentialsProvider.java:51)
        at org.hibernate.build.publish.auth.maven.MavenRepoAuthPlugin.apply(MavenRepoAuthPlugin.java:21)
        at org.hibernate.build.publish.auth.maven.MavenRepoAuthPlugin.apply(MavenRepoAuthPlugin.java:17)
...
```

**Comment by scholzi100** [comment]
Can confirm on this, same problem over here.
